version: '3.7'

services:
  django_gunicorn:
    container_name: card_django
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8100:8000"
    networks:
      - nginx_network
    depends_on:
      - postgres

  nginx:
    container_name: card_nginx
    build:
      context: ./nginx
      args:
        ENV_CONF: ${NGINX_CONF}   
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
    networks:
      - nginx_network

  postgres:
    image: postgres:14.4-bullseye
    container_name: card_postgres
    networks:
      - nginx_network
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"

volumes:
  static:
  media:
  postgres_data:

networks:
  nginx_network:
    driver: bridge