version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
      - ./backend:/app

  nginx:
    volumes:
      - static:/static
      - ./media:/media
    ports:
      - "80:80"

  postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data/