version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
      - ./backend:/app

  nginx:
    volumes:
      - ./certs:/etc/ssl/certs:ro
      - static:/static
      - ./media:/media

  postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data/