# Generated by Django 4.0.6 on 2024-05-02 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('phrase', models.JSONField()),
                ('image_url', models.TextField()),
                ('cover_url', models.TextField()),
                ('visible', models.BooleanField()),
                ('code', models.CharField(max_length=20)),
                ('meaning', models.JSONField(blank=True, null=True)),
                ('examples', models.JSONField(blank=True, null=True)),
                ('scenarios', models.JSONField(blank=True, null=True)),
                ('explanations', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClusterCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('image_url', models.TextField()),
                ('cover_url', models.TextField()),
                ('code', models.CharField(max_length=20)),
                ('cluster', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('visible', models.BooleanField()),
                ('image_url', models.TextField()),
                ('cover_url', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('phrase', models.JSONField()),
                ('meaning', models.JSONField(blank=True, null=True)),
                ('examples', models.JSONField(blank=True, null=True)),
                ('sticker_code', models.CharField(max_length=20)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('code', models.CharField(max_length=20)),
                ('extras', models.JSONField(blank=True, null=True)),
                ('basic_cards', models.ManyToManyField(to='cards.basiccard')),
                ('cluster_cards', models.ManyToManyField(to='cards.clustercard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
