# Generated by Django 4.0.6 on 2024-05-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basiccard',
            name='voice_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
