# Generated by Django 4.0.6 on 2024-05-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_basiccard_voice_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basiccard',
            name='voice_url',
        ),
        migrations.AddField(
            model_name='basiccard',
            name='voice',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
