# Generated by Django 4.0.6 on 2024-05-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_basiccard_voice_url_basiccard_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='basiccard',
            name='vocab',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
