# Generated by Django 4.0.6 on 2024-05-11 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_basiccard_vocab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basiccard',
            old_name='vocab',
            new_name='vocabs',
        ),
    ]
