# Generated by Django 4.0.6 on 2024-05-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_rename_vocab_basiccard_vocabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='basiccard',
            name='compare',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
