# Generated by Django 4.0.6 on 2024-05-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_basiccard_compare'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cards',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
