# Generated by Django 4.0.6 on 2024-05-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_category_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tab_height',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
